### ISSUE TITLE
"Thermostat" incorrect for Celcius

### ISSUE THREAD

**Issue by DaveHarrington** [valiquette/homebridge-my-wallbox#10]
Hi! Thanks for your great work here. I noticed that the "thermostat" is showing -18C at the 0 point, I assume the plugin doesn't convert from Fahrenheit today. I'm happy to try writing a patch if you can point me in the right direction!

**Comment by valiquette** [comment]
The plugin is only using Celsius, but it seems the region setting changes it and It was tuned for Fahrenheit, and since this is not a real tempature but rather a fixed range from 0 to 40 or 48 which is why I use the thermostat everything else is a % which got confusing. I would need to find a way to detect that or add a config setting.  The fix should be quick and easy if I can figure out how best to detect.

**Comment by valiquette** [comment]
I seems like I can correct his by just forcing the display to be C regardless of the device region setting.

**Comment by valiquette** [comment]
beta 5 should correct this, there is no way to address this directly with Wallbox. I have added a choice in the config to pick between F or C thermostats. The only different is you will see a decimal .0 being C.

**Comment by DaveHarrington** [comment]
Thank you! I’ll check it out.

**Comment by valiquette** [comment]
Corrected in v1.0.14
